"use strict";

module.exports = {
  apps: [
    {
      name: "rtc-signal",
      script: "./server.js",
      cwd: process.env.PM2_APP_CWD || "/opt/rtc-signal",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_memory_restart: process.env.PM2_MAX_MEMORY || "700M",
      kill_timeout: Number(process.env.PM2_KILL_TIMEOUT || 5000),
      listen_timeout: Number(process.env.PM2_LISTEN_TIMEOUT || 10000),
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        RTC_CLUSTER_ENABLED: "0",
        RTC_REDIS_URL: process.env.RTC_REDIS_URL || "redis://127.0.0.1:6379",
        RTC_WS_RECONNECT_GRACE_MS: process.env.RTC_WS_RECONNECT_GRACE_MS || "45000",
        WS_HEARTBEAT_MS: process.env.WS_HEARTBEAT_MS || "20000",
        WS_HEARTBEAT_MISS_LIMIT: process.env.WS_HEARTBEAT_MISS_LIMIT || "3",
        PROFILE_STORE_BACKEND: process.env.PROFILE_STORE_BACKEND || "sqlite",
        PROFILE_SQLITE_PATH: process.env.PROFILE_SQLITE_PATH || "/opt/rtc-signal/data/profiles.db",
        PROFILE_PERSIST_BATCH_MS: process.env.PROFILE_PERSIST_BATCH_MS || "800",
        PUBLIC_BASE_URL: process.env.PUBLIC_BASE_URL || "https://comspc.duckdns.org",
        AUTH_PUBLIC_BASE_URL: process.env.AUTH_PUBLIC_BASE_URL || process.env.PUBLIC_BASE_URL || "https://comspc.duckdns.org",
        GOOGLE_WEB_CLIENT_ID: process.env.GOOGLE_WEB_CLIENT_ID || "184465159535-c97fk9vrki1vuk8r6t38ngkj4mt6s5gg.apps.googleusercontent.com",
        GOOGLE_IOS_CLIENT_ID: process.env.GOOGLE_IOS_CLIENT_ID || "",
        APPLE_NATIVE_CLIENT_ID: process.env.APPLE_NATIVE_CLIENT_ID || "com.ranchat",
        APPLE_BUNDLE_ID: process.env.APPLE_BUNDLE_ID || process.env.APPLE_NATIVE_CLIENT_ID || "com.ranchat",
        AI_REPLY_ENABLED: process.env.AI_REPLY_ENABLED || "1",
        AI_REPLY_SERVICE_BASE_URL: process.env.AI_REPLY_SERVICE_BASE_URL || "http://127.0.0.1:3002",
        AI_REPLY_OLLAMA_BASE_URL: process.env.AI_REPLY_OLLAMA_BASE_URL || "http://127.0.0.1:11434",
        AI_REPLY_OLLAMA_MODEL: process.env.AI_REPLY_OLLAMA_MODEL || "gemma3:1b-it-qat",
        AI_REPLY_TIMEOUT_MS: process.env.AI_REPLY_TIMEOUT_MS || "12000",
        AI_REPLY_MAX_REPLY_LEN: process.env.AI_REPLY_MAX_REPLY_LEN || "120",
        AI_REPLY_MAX_LINES: process.env.AI_REPLY_MAX_LINES || "2",
        AI_REPLY_HISTORY_MAX_USER_MESSAGES: process.env.AI_REPLY_HISTORY_MAX_USER_MESSAGES || "4",
        AI_REPLY_HISTORY_MAX_ASSISTANT_MESSAGES: process.env.AI_REPLY_HISTORY_MAX_ASSISTANT_MESSAGES || "4",
        AI_REPLY_NUM_CTX: process.env.AI_REPLY_NUM_CTX || "320",
        AI_REPLY_NUM_PREDICT: process.env.AI_REPLY_NUM_PREDICT || "18",
        AI_REPLY_NUM_THREAD: process.env.AI_REPLY_NUM_THREAD || "3",
      },
    },
    {
      name: "ai-reply-worker",
      script: "./ai_reply_worker.js",
      cwd: process.env.PM2_APP_CWD || "/opt/rtc-signal",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_memory_restart: process.env.PM2_AI_MAX_MEMORY || "512M",
      kill_timeout: Number(process.env.PM2_KILL_TIMEOUT || 5000),
      listen_timeout: Number(process.env.PM2_LISTEN_TIMEOUT || 10000),
      env: {
        NODE_ENV: "production",
        AI_REPLY_WORKER_PORT: process.env.AI_REPLY_WORKER_PORT || "3002",
        AI_REPLY_OLLAMA_BASE_URL: process.env.AI_REPLY_OLLAMA_BASE_URL || "http://127.0.0.1:11434",
        AI_REPLY_OLLAMA_MODEL: process.env.AI_REPLY_OLLAMA_MODEL || "gemma3:1b-it-qat",
        AI_REPLY_TIMEOUT_MS: process.env.AI_REPLY_TIMEOUT_MS || "12000",
        AI_REPLY_MAX_REPLY_LEN: process.env.AI_REPLY_MAX_REPLY_LEN || "120",
        AI_REPLY_MAX_LINES: process.env.AI_REPLY_MAX_LINES || "2",
        AI_REPLY_HISTORY_MAX_USER_MESSAGES: process.env.AI_REPLY_HISTORY_MAX_USER_MESSAGES || "4",
        AI_REPLY_HISTORY_MAX_ASSISTANT_MESSAGES: process.env.AI_REPLY_HISTORY_MAX_ASSISTANT_MESSAGES || "4",
        AI_REPLY_NUM_CTX: process.env.AI_REPLY_NUM_CTX || "320",
        AI_REPLY_NUM_PREDICT: process.env.AI_REPLY_NUM_PREDICT || "18",
        AI_REPLY_NUM_THREAD: process.env.AI_REPLY_NUM_THREAD || "3",
      },
    },
  ],
};

