import { Dimensions, StyleSheet } from "react-native";
import { theme } from "../config/theme";

export const W = Dimensions.get("window").width;

const REMOTE_VIDEO_SCALE = 1.22;
const REMOTE_SHIFT_Y = 0;
export const REMOTE_VIDEO_Z_ORDER = 0;
export const LOCAL_VIDEO_Z_ORDER = 1;

const LOCAL_CROP_Y = 0;
const LOCAL_OVERLAY_RADIUS = 25;
const LOCAL_OUTER_SHADOW_HEIGHT = 60;

export const OVERLAY_LOCAL_HEIGHT_CALLING = "45%";


export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#000" },

  stage: { flex: 1, position: "relative", backgroundColor: "#000" },

  overlayStage: { flex: 1 },

  localLayer: {
  ...StyleSheet.absoluteFillObject,
  zIndex: 30,
  elevation: 30,
},

localAreaShadow: {
  position: "absolute",
  left: 0,
  right: 0,
  height: "50%",
  backgroundColor: "transparent",
  overflow: "hidden",
  zIndex: 3,
  borderTopLeftRadius: LOCAL_OVERLAY_RADIUS,
  borderTopRightRadius: LOCAL_OVERLAY_RADIUS,
},

localTopShadowGradient: {
  position: "absolute",
  left: 0,
  right: 0,
  height: LOCAL_OUTER_SHADOW_HEIGHT,
  overflow: "hidden",
  zIndex: 4,
  transform: [{ translateY: 0 }],
},

localArea: {
  ...StyleSheet.absoluteFillObject,
  backgroundColor: "#000000",
  overflow: "hidden",
  borderTopLeftRadius: LOCAL_OVERLAY_RADIUS,
  borderTopRightRadius: LOCAL_OVERLAY_RADIUS,
  borderTopWidth: StyleSheet.hairlineWidth,
  borderLeftWidth: StyleSheet.hairlineWidth,
  borderRightWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,255,255,0.16)",
},

localAreaCalling: {
  height: OVERLAY_LOCAL_HEIGHT_CALLING,
},

  remoteLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    elevation: 10,
  },

  remoteArea: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    borderRadius: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: "#000",
    overflow: "hidden",
  },

  remoteVideo: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
    transform: [{ scale: REMOTE_VIDEO_SCALE }, { translateY: REMOTE_SHIFT_Y }],
  },

  placeholder: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", backgroundColor: "#000" },
  placeholderText: { fontSize: 14, color: "rgba(255,255,255,0.75)", fontWeight: "700" },

  backBtn: {
    position: "absolute",
    zIndex: 120,
    elevation: 120,
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  shopBtn: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  giftSendBtn: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  callSafetyBtn: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  callAiStopBtn: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  callContactsBtn: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  callContactQuickBtn: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  callContactQuickBtnActive: {
    backgroundColor: "rgba(120,39,74,0.58)",
    borderWidth: 1,
    borderColor: "rgba(255,225,236,0.42)",
  },
  callAiStopBtnPressed: {
    opacity: 0.76,
  },
  callTranslateBtn: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(20,20,20,0.34)",
  },
  callTranslateBtnActive: {
    backgroundColor: "rgba(26,108,130,0.34)",
    borderWidth: 1,
    borderColor: "rgba(172,237,255,0.42)",
  },
  liveTranslateStatusWrap: {
    position: "absolute",
    zIndex: 145,
    elevation: 145,
    maxWidth: 160,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(172,237,255,0.42)",
    backgroundColor: "rgba(26,108,130,0.34)",
    alignItems: "center",
    justifyContent: "center",
  },
  liveTranslateStatusText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: "rgba(229,248,255,0.98)",
  },
  callSafetyBtnText: {
    fontSize: 21,
    color: "#EFEFEF",
    fontWeight: "900",
    textAlign: "center",
    includeFontPadding: false,
    lineHeight: 22,
  },

  topUiLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 140,
    elevation: 140,
  },

  remoteInfoDock: {
    position: "absolute",
    top: 0,
    left: 16,
    right: 16,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    elevation: 50,
    gap: 3,
  },

  remoteProfileDock: {
    position: "absolute",
    top: 0,
    right: 4,
    width: 88,
    alignItems: "center",
    justifyContent: "flex-start",
    zIndex: 50,
    elevation: 50,
    gap: 4,
  },

  remoteInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    maxWidth: "100%",
  },
  remoteInfoRowAi: {
    gap: 14,
  },

  remoteInfoMetaWrap: {
    flexShrink: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    maxWidth: 280,
  },
  remoteInfoMetaWrapAi: {
    gap: 0,
  },
  remoteInfoMetaLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    maxWidth: 300,
  },

  remoteInfoProfileWrap: {
    width: 88,
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 4,
  },
  remoteInfoProfileWrapAi: {
    marginLeft: 4,
  },

  aiPeerBadge: {
    backgroundColor: "rgba(45,45,50,0.96)",
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 3,
    minWidth: 34,
    alignItems: "center",
    justifyContent: "center",
  },

  aiPeerBadgeText: {
    color: "#FF67BC",
    fontSize: 15,
    fontWeight: "900",
    lineHeight: 17,
  },

  remoteInfoText: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 16,
    maxWidth: 286,
    textAlign: "center",
  },

  remoteInfoNicknameText: {
    color: "rgba(255,240,246,0.98)",
    fontSize: 11,
    fontWeight: "800",
    maxWidth: 96,
    textAlign: "center",
    lineHeight: 13,
  },

  remoteInfoAvatarWrap: {
    width: 50,
    height: 50,
    borderRadius: 999,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    backgroundColor: "rgba(74,54,65,0.96)",
  },

  remoteInfoAvatarImage: {
    width: "100%",
    height: "100%",
  },

  remoteInfoAvatarFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(86,62,76,0.98)",
  },

  remoteInfoSubText: {
    color: "rgba(255, 170, 170, 0.92)",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },

  localViewport: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
    overflow: "hidden",
  },

  localVideoMover: {
    ...StyleSheet.absoluteFillObject,
    transform: [{ translateY: -LOCAL_CROP_Y }],
  },

  localVideoFull: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
    transform: [{ scale: 1 }],
  },

  localEmptyFull: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
  },

  localCamOffBgFull: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
  },

  camOffOverlayFull: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 34,
    backgroundColor: "#000",
  },
  camOffAvatarDock: {
    marginTop: 36,
  },
  camOffAvatarWaveWrap: {
    width: 148,
    height: 148,
    alignItems: "center",
    justifyContent: "center",
  },

  stageAvatarWrapLarge: {
    width: 92,
    height: 92,
    borderRadius: 999,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    backgroundColor: "rgba(76,56,68,0.98)",
  },
  stageAvatarWrapMuted: {
    borderWidth: 1.5,
    borderColor: "rgba(111, 18, 60, 0.92)",
  },
  stageAvatarImage: {
    width: "100%",
    height: "100%",
  },
  stageAvatarFallbackLarge: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(86,62,76,0.98)",
  },
  stageAvatarDimOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.34)",
  },
  stageAvatarMuteBadge: {
    position: "absolute",
    right: 2,
    bottom: 2,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(91, 16, 56, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255, 228, 240, 0.34)",
  },
  localMicWaveRingPrimary: {
    position: "absolute",
    width: 102,
    height: 102,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "rgba(235, 195, 226, 0.78)",
    backgroundColor: "rgba(235, 195, 226, 0.05)",
  },
  localMicWaveRingSecondary: {
    position: "absolute",
    width: 104,
    height: 104,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "rgba(222, 178, 217, 0.62)",
    backgroundColor: "transparent",
  },

  centerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  giftFxOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 125,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  giftFxAnimWrap: {
    width: 244,
    height: 244,
    alignItems: "center",
    justifyContent: "center",
  },
  giftFxGlow: {
    position: "absolute",
    width: 186,
    height: 186,
    borderRadius: 93,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.62)",
    shadowColor: "#FFFFFF",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
    zIndex: 0,
  },
  giftFxPulseRing: {
    position: "absolute",
    width: 184,
    height: 184,
    borderRadius: 92,
    borderWidth: 2,
    zIndex: 1,
  },
  giftFxCoreWhite: {
    position: "absolute",
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.98)",
    zIndex: 2,
  },
  giftFxSparkLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 3,
  },
  giftFxSpark: {
    position: "absolute",
    textShadowColor: "rgba(0,0,0,0.32)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  giftFxSparkTop: {
    top: 28,
    left: 114,
  },
  giftFxSparkRight: {
    top: 106,
    right: 24,
  },
  giftFxSparkBottom: {
    bottom: 26,
    left: 120,
  },
  giftFxSparkLeft: {
    top: 98,
    left: 24,
  },
  giftFxSparkSend: {
    color: "#FFFDF2",
  },
  giftFxSparkReceive: {
    color: "#FFEFCF",
  },
  giftFxImage: {
    width: 166,
    height: 166,
    zIndex: 4,
  },
  giftFxNoticeWrap: {
    position: "absolute",
    minWidth: 220,
    maxWidth: "88%",
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  giftFxNoticeRaised: {
    top: "28%",
  },
  giftFxNoticeCenter: {
    top: "46%",
  },
  giftFxNoticeText: {
    fontSize: 16,
    color: "#FFF9FF",
    fontWeight: "900",
    textAlign: "center",
    lineHeight: 22,
    textShadowColor: "rgba(0,0,0,0.45)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  giftFxText: {
    fontSize: 14,
    color: "rgba(255,235,246,0.96)",
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 19,
  },
  matchRevealBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
  },
  matchRevealHeartWrap: {
    position: "absolute",
    width: 164,
    height: 150,
    alignItems: "center",
    justifyContent: "center",
  },
  matchRevealPiece: {
    position: "absolute",
    overflow: "hidden",
    backgroundColor: "#000",
  },
  matchRevealLobeLeft: {
    left: 22,
    top: 0,
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  matchRevealLobeRight: {
    left: 78,
    top: 0,
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  matchRevealBottomDiamond: {
    left: 36,
    top: 30,
    width: 92,
    height: 92,
    borderRadius: 16,
    transform: [{ rotate: "45deg" }],
  },
  matchRevealVideo: {
    ...StyleSheet.absoluteFillObject,
  },
  matchRevealVideoDiamond: {
    ...StyleSheet.absoluteFillObject,
    transform: [{ rotate: "-45deg" }, { scale: 1.42 }],
  },
  matchRevealHeartGlow: {
    position: "absolute",
    top: -16,
    textShadowColor: "rgba(255, 214, 236, 0.9)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  matchRevealHeartFill: {
    position: "absolute",
    top: 2,
    textShadowColor: "rgba(255, 240, 248, 0.75)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 7,
  },

  centerTextDock: {
    position: "absolute",
    left: 18,
    right: 18,
    top: "50%",
    marginTop: 52,
    minHeight: 72,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  centerTextMainWrap: {
    width: "100%",
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
  },
  matchingActionsDock: {
    width: "100%",
    alignItems: "center",
    marginTop: 52,
  },

  centerText: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "600",
    color: "rgba(139, 139, 139, 0.85)",
    lineHeight: 24,
  },
  matchingActionsDesc: {
    maxWidth: "92%",
    textAlign: "center",
    fontSize: 15,
    lineHeight: 22,
    color: "rgba(164,164,164,0.96)",
    fontWeight: "500",
  },
  matchingHintRow: {
    marginTop: 10,
    maxWidth: "92%",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    backgroundColor: "rgba(0,0,0,0.26)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  matchingHintText: {
    fontSize: 12,
    lineHeight: 16,
    color: "rgba(212,212,212,0.92)",
    fontWeight: "700",
  },
  matchingActionRow: {
    width: "100%",
    maxWidth: 360,
    marginTop: 16,
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: 8,
  },
  matchingActionBtn: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(0,0,0,0.34)",
    paddingHorizontal: 6,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  matchingActionBtnPressed: {
    opacity: 0.72,
  },
  matchingActionIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  matchingActionLabel: {
    marginTop: 4,
    fontSize: 11,
    lineHeight: 14,
    color: "rgba(236,236,236,0.96)",
    fontWeight: "800",
    textAlign: "center",
  },

  reMatchTextWrap: {
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
  },

  reMatchTextTop: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "600",
    color: "rgba(139, 139, 139, 0.85)",
    lineHeight: 24,
  },

  reMatchTextBottom: {
    textAlign: "center",
    fontSize: 24,
    fontWeight: "800",
    color: "rgba(139, 139, 139, 0.85)",
    lineHeight: 28,
    marginTop: 4,
  },

  queueAdDock: {
    position: "absolute",
    zIndex: 11,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  swipeGuideDock: {
    position: "absolute",
    right: 22,
    top: "50%",
    transform: [{ translateY: -56 }],
    zIndex: 115,
    elevation: 115,
    alignItems: "flex-end",
  },
  swipeGuideTextWrap: {
    width: 180,
    alignItems: "stretch",
    justifyContent: "center",
    marginBottom: 2,
    marginRight: 12,
  },
  swipeGuideTextTop: {
    width: "100%",
    textAlign: "right",
    fontSize: 21,
    lineHeight: 25,
    fontWeight: "900",
    color: "rgba(255,255,255,0.9)",
  },
  swipeGuideTextBottom: {
    width: "100%",
    textAlign: "right",
    fontSize: 36,
    lineHeight: 40,
    fontWeight: "900",
    color: "rgba(255,255,255,0.95)",
    marginTop: 2,
  },
  swipeGuideImage: {
    width: 112,
    height: 112,
    opacity: 0.94,
  },

  nativeAd256: {
    width: 360,
    height: 202,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  nativeAdInner: {
    flex: 1,
  },
  nativeAdMedia: {
    flex: 1,
  },
  nativeAdFooter: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "rgba(0,0,0,0.55)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  nativeAdHeadline: {
    flex: 1,
    fontSize: 12,
    color: "rgba(255,255,255,0.92)",
    fontWeight: "800",
  },
  nativeAdTag: {
    fontSize: 11,
    color: "rgba(255,255,255,0.75)",
    fontWeight: "900",
  },

  controlsOverlay: {
    position: "absolute",
    zIndex: 160,
    elevation: 160,
    left: 0,
    right: 0,
    alignItems: "center",
  },

  chatFeedUnderShadow: {
    position: "absolute",
    top: 0,
    left: 12,
    right: 12,
    height: 156,
    justifyContent: "flex-end",
    gap: 6,
    overflow: "visible",
    zIndex: 65,
    elevation: 65,
  },
  chatFeedRow: {
    width: "100%",
    flexDirection: "row",
  },
  chatFeedRowMine: {
    justifyContent: "flex-end",
  },
  chatFeedRowPeer: {
    justifyContent: "flex-start",
  },
  chatFeedCluster: {
    maxWidth: "90%",
    gap: 4,
  },
  chatFeedClusterMine: {
    alignSelf: "flex-end",
    alignItems: "flex-end",
  },
  chatFeedClusterPeer: {
    alignSelf: "flex-start",
    alignItems: "flex-start",
  },
  chatFeedMessageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    maxWidth: "100%",
  },
  chatFeedMessageRowMine: {
    justifyContent: "flex-end",
  },
  chatFeedMessageRowPeer: {
    justifyContent: "flex-start",
  },
  chatFeedBubble: {
    flexShrink: 1,
    maxWidth: "100%",
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    justifyContent: "center",
  },
  chatFeedBubbleMine: {
    backgroundColor: "rgba(79, 51, 64, 0.84)",
    borderTopRightRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255, 224, 233, 0.2)",
  },
  chatFeedBubblePeer: {
    backgroundColor: "rgba(88, 56, 70, 0.78)",
    borderTopLeftRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255, 226, 235, 0.16)",
  },
  chatFeedBubbleGiftMine: {
    backgroundColor: "rgba(108, 92, 132, 0.64)",
    borderWidth: 1,
    borderColor: "rgba(234, 223, 255, 0.45)",
  },
  chatFeedBubbleGiftPeer: {
    backgroundColor: "rgba(124, 104, 148, 0.56)",
    borderWidth: 1,
    borderColor: "rgba(232, 220, 255, 0.4)",
  },
  chatFeedText: {
    color: "#fff",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    includeFontPadding: false,
  },
  chatFeedTextNewest: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
  },
  chatFeedTextGift: {
    color: "#F6EEFF",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  chatFeedTextGiftNewest: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
  },
  chatComposerDock: {
    width: "100%",
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  chatComposerDockHidden: {
    opacity: 0,
    transform: [{ translateY: 20 }],
  },
  chatComposerOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 120,
    elevation: 120,
  },
  chatComposerOverlayHidden: {
    opacity: 0,
  },
  chatComposerModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.01)",
  },
  chatComposerBackdropHit: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  chatComposerModalWrap: {
    flex: 1,
    justifyContent: "flex-end",
  },
  chatInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  chatInput: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 0,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    textAlignVertical: "center",
    color: "#fff",
    backgroundColor: "rgba(0, 0, 0, 0.52)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.24)",
  },
  chatSendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3f323770",
  },

  controlsRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    paddingHorizontal: 12,
  },

  controlBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3f323770",
  },
  callSafetyGuideText: {
    width: "100%",
    fontSize: 14,
    color: theme.colors.sub,
    lineHeight: 20,
    textAlign: "center",
  },
  callAiStopBtnText: {
    fontSize: 19,
    color: "#111111",
    fontWeight: "900",
    textAlign: "center",
    includeFontPadding: false,
    lineHeight: 20,
  },
  callReportReasonList: {
    width: "100%",
    gap: 8,
    paddingBottom: 2,
  },
  callReportReasonScroll: {
    width: "100%",
    maxHeight: 300,
  },
  callReportReasonRow: {
    width: "100%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(191,194,208,0.72)",
    backgroundColor: "rgba(249,250,255,0.92)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  callReportReasonRowActive: {
    borderColor: "rgba(176,30,86,0.88)",
    backgroundColor: "rgba(255,240,247,0.96)",
  },
  callReportReasonTextWrap: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 2,
  },
  callReportReasonTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: "#2C2F3A",
    textAlign: "left",
  },
  callReportReasonTitleActive: {
    color: "#9D174D",
  },
  callReportReasonDescription: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: "#5C6375",
    textAlign: "left",
  },
  callContactsScroll: {
    width: "100%",
    maxHeight: 400,
    marginTop: 6,
  },
  callContactsList: {
    width: "100%",
    gap: 10,
    paddingBottom: 4,
  },
  callContactRow: {
    width: "100%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(191,194,208,0.72)",
    backgroundColor: "rgba(249,250,255,0.96)",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  callContactRowTop: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  callContactTextWrap: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 6,
  },
  callContactBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  callContactBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(176,30,86,0.24)",
    backgroundColor: "rgba(255,240,247,0.96)",
  },
  callContactBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    color: "#9D174D",
  },
  callContactTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: "#2C2F3A",
    textAlign: "left",
  },
  callContactMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    color: "#5C6375",
    textAlign: "left",
  },
  callContactStatusWaiting: {
    color: "#9D174D",
  },
  callContactStatusOnline: {
    color: theme.colors.ok,
  },
  callContactStatusOffline: {
    color: "#7B8190",
  },
  callContactActionBtn: {
    minWidth: 104,
    height: 44,
  },
  callContactActionBtnText: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  callContactEmptyText: {
    width: "100%",
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.sub,
    textAlign: "center",
  },
  modalText: { width: "100%", fontSize: 14, color: theme.colors.sub, lineHeight: 20, textAlign: "center" },
  recallAcceptedModalBody: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 10,
  },
  recallAcceptedHeartWrap: {
    width: 86,
    height: 86,
    borderRadius: 43,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,98,156,0.14)",
  },
  recallAcceptedHeartText: {
    fontSize: 42,
    fontWeight: "900",
    color: theme.colors.pinkDeep,
    lineHeight: 48,
    textAlign: "center",
  },
  matchFilterScroll: {
    width: "100%",
    maxHeight: 360,
    marginTop: 6,
  },
  matchFilterScrollContent: {
    gap: 10,
    paddingBottom: 4,
  },
  matchFilterOptionWrap: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  matchFilterCountryOptionWrap: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 8,
  },
  matchFilterLanguageOptionWrap: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 8,
  },
  matchFilterInterestOptionWrap: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  matchFilterOption: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(191,194,208,0.72)",
    backgroundColor: "rgba(249,250,255,0.92)",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  matchFilterCountryOption: {
    width: "31.7%",
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  matchFilterLanguageOption: {
    width: "48.6%",
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  matchFilterInterestOption: {
    minHeight: 40,
  },
  matchFilterOptionActive: {
    borderColor: "rgba(176,30,86,0.88)",
    backgroundColor: "rgba(255,240,247,0.96)",
  },
  matchFilterOptionPressed: {
    opacity: 0.78,
  },
  matchFilterOptionText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
    color: "#394055",
  },
  matchFilterCountryOptionText: {
    fontSize: 12,
    lineHeight: 15,
    textAlign: "center",
  },
  matchFilterLanguageOptionText: {
    textAlign: "center",
  },
  matchFilterInterestOptionText: {
    fontSize: 12,
    lineHeight: 16,
  },
  matchFilterOptionTextActive: {
    color: "#9D174D",
  },

  sectionTitle: { width: "100%", fontSize: 14, fontWeight: "700", color: theme.colors.text, textAlign: "center" },

  dropdownBtn: {
    width: "100%",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.card,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownBtnText: { fontSize: 14, color: theme.colors.text, fontWeight: "700" },
  dropdownChevron: { fontSize: 12, color: theme.colors.sub, fontWeight: "900" },

  dropdownList: {
    width: "100%",
    marginTop: 8,
    gap: 8,
  },

  dropdownListWrap: {
    width: "100%",
    marginTop: 8,
    borderRadius: 12,
    overflow: "hidden",
  },
  dropdownScroll: {
    maxHeight: 210,
  },
  dropdownScrollContent: {
    gap: 8,
  },

  dropdownRow: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.card,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownRowActive: {
    backgroundColor: theme.colors.cardSoft,
  },
  dropdownText: { fontSize: 14, color: theme.colors.text, fontWeight: "700" },
  dropdownTextActive: { color: theme.colors.pinkDeep },
  dropdownCheck: { fontSize: 14, color: theme.colors.pinkDeep, fontWeight: "900" },

  countryRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  countryCode: { fontSize: 12, color: theme.colors.sub, fontWeight: "800" },
  countryCodeActive: { color: theme.colors.pinkDeep },
});

