export const POPTALK_MATCH_BLOCK_THRESHOLD = 20;
export const POPTALK_LOW_WARNING_THRESHOLD = 40;

export const POPTALK_CALL_COST_PER_SECOND = 1;
export const POPTALK_CHAT_COST_PER_MESSAGE = 1;
export const POPTALK_CHAT_TRANSLATE_RECEIVE_COST_PER_MESSAGE = 2;
export const POPTALK_REWARDED_AMOUNT = 500;

export const POPTALK_REFRESH_INTERVAL_MS = 30000;
